### ISSUE TITLE
No permission error

### ISSUE THREAD

**Issue by JeremyStarTM** [konkitoman/autoclicker#1]
I'm currently running the latest version of Manjaro with Kernel 5.10.60-1.
I can't run the AutoClicker from source or the releases tab, since it exits with this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/device.rs:26:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with RUST_BACKTRACE=1:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/device.rs:26:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: theclicker::device::Device::dev_open
   4: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: theclicker::device::Device::select_device
   7: theclicker::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Running with RUST_BACKTRACE=full:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/device.rs:26:38
stack backtrace:
   0:     0x556d8adfaba0 - std::backtrace_rs::backtrace::libunwind::trace::h34055254b57d8e79
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x556d8adfaba0 - std::backtrace_rs::backtrace::trace_unsynchronized::h8f1e3fbd9afff6ec
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x556d8adfaba0 - std::sys_common::backtrace::_print_fmt::h3a99a796b770c360
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x556d8adfaba0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h32d1f94a80615d18
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x556d8ae1585c - core::fmt::write::h306731c068f7162c
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/fmt/mod.rs:1110:17
   5:     0x556d8adf8dc5 - std::io::Write::write_fmt::hd2fa90334eee2a21
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/io/mod.rs:1588:15
   6:     0x556d8adfcc9b - std::sys_common::backtrace::_print::h5abaa2601a852287
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x556d8adfcc9b - std::sys_common::backtrace::print::h8d81445442bb638f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x556d8adfcc9b - std::panicking::default_hook::{{closure}}::hcfe804496a9fa747
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:208:50
   9:     0x556d8adfc771 - std::panicking::default_hook::hbea8e3ccf2ba8901
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:225:9
  10:     0x556d8adfd364 - std::panicking::rust_panic_with_hook::h7ee9e1a2d0f8975a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:622:17
  11:     0x556d8adfce47 - std::panicking::begin_panic_handler::{{closure}}::h8ab3b4491718b2c7
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:519:13
  12:     0x556d8adfb09c - std::sys_common::backtrace::__rust_end_short_backtrace::hd489062ffa586a9f
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x556d8adfcda9 - rust_begin_unwind
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
  14:     0x556d8adde3b1 - core::panicking::panic_fmt::hca6330e3e14086b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
  15:     0x556d8adde443 - core::result::unwrap_failed::h6160d2b4bfbb0e87
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
  16:     0x556d8ade4209 - theclicker::device::Device::dev_open::h3ba4e95e7b06c749
  17:     0x556d8ade1952 - <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next::h995798e52f1b7155
  18:     0x556d8ade1e2b - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h3da8d4240831c2fe
  19:     0x556d8ade48cc - theclicker::device::Device::select_device::h235e1fa901cdaee8
  20:     0x556d8addfb3d - theclicker::main::hd0dc7f34d7bd1598
  21:     0x556d8ade33d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ab4eb43bb986add
  22:     0x556d8ade6869 - std::rt::lang_start::{{closure}}::h495330ce79becc0b
  23:     0x556d8adfd869 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2aabc384aab89b7b
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/ops/function.rs:259:13
  24:     0x556d8adfd869 - std::panicking::try::do_call::hc5fcacb7a85fc7b1
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:401:40
  25:     0x556d8adfd869 - std::panicking::try::hb5d9603af3abbe3a
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:365:19
  26:     0x556d8adfd869 - std::panic::catch_unwind::h98fe6ac3925e64b4
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panic.rs:434:14
  27:     0x556d8adfd869 - std::rt::lang_start_internal::h22ac7383c516f93e
                               at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/rt.rs:34:21
  28:     0x556d8ade1262 - main
  29:     0x7ffb709e9b25 - __libc_start_main
  30:     0x556d8addeb2e - _start
  31:                0x0 - <unknown>
```

The application always exists with code 101.

**Comment by konkitoman** [comment]
If you run with sudo:
   cargo build
   sudo ./target/debug/theclicker
You get that error?

If not run:
   sudo usermod -aG input "Your user"
You can run without sudo, theclicker or cargo run

**Comment by JeremyStarTM** [comment]
Tried that already, but nothing helped me. :(

**Comment by konkitoman** [comment]
cd /dev/input and enter ll and send me the output

**Comment by JeremyStarTM** [comment]
Okay, I try that when I'm back home. When it works, I respond here

**Comment by konkitoman** [comment]
Thanks!

**Comment by JeremyStarTM** [comment]
Okay, works now. Thanks for the help :D

**Comment by JeremyStarTM** [comment]
Edited some of the messages so no eyes can bleed.

**Comment by konkitoman** [comment]
Nice!
